### ISSUE TITLE
error: getting status of '/nix/store/wr2nlm620rghs2gl2rplw7440vpcwczx-source/bashrc': No such file or directory

### ISSUE THREAD

**Issue by shauryagoel** [Arkham/dotfiles.nix#1]
Thanks for your amazing config and blog. I was following your blog and encountered the above error when using programs.bash (I also get a similar error in ./profile). 

My OS is Arch Linux
My nix version is 2.13.3
My home-manager version is 23.05-pre

Do you have any idea how to resolve it?

**Comment by Arkham** [comment]
hey @shauryagoel, thanks for checking out my blog post :) Could it be it's because you don't have a `bashrc` or `bash_profile` in your home? In that case, these lines wouldn't do anything at all:
```bash
$ cd ~/.config/nixpkgs
$ cp -L ~/.bashrc bashrc
$ cp -L ~/.bash_profile bash_profile
```

So in your `home.nix` replace this block:
```
  programs.bash = {
    enable = true;
    profileExtra = builtins.readFile ./bash_profile;
    initExtra = builtins.readFile ./bashrc;
  };
```

with just

```
  programs.bash = {
    enable = true;
  };
```

And I guess this will fix your problem :)

**Comment by shauryagoel** [comment]
Hi @Arkham, this actually resolved my issue.  I had been trying to solve the issue for many hours, but couldn't solve it. It was my stupid mistake. Thanks for your support.
